version: '3'

services:
  notify:
    image: node:11.10-stretch
    ports:
      - 80:3000
    volumes:
      - ./:/app
    working_dir: /app
    command: node index.js
    environment:
      - NODE_ENV=staging
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    links:
      - notify
