version: '3'

services:
  notify:
    build: .
    image: notify
    ports:
      - 80:3000
    volumes:
      - ./:/app

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    links:
      - notify
